<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>MachSoft.UI.Showcase</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../MachSoft.UI/MachSoft.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
  </ItemGroup>
</Project>
