namespace Machsoft.DesignSystem.Theme;

public sealed record DesignTokens(
    string ColorPrimary,
    string ColorPrimaryDark,
    string ColorSecondary,
    string ColorBackground,
    string ColorSurface,
    string ColorTextPrimary,
    string ColorTextSecondary,
    string ColorBorder,
    string ColorOverlay,
    string RadiusSm,
    string RadiusMd,
    string RadiusLg,
    string SpacingXs,
    string SpacingSm,
    string SpacingMd,
    string SpacingLg,
    string FontSizeSm,
    string FontSizeMd,
    string FontSizeLg,
    string FontWeightBody,
    string FontWeightHeading)
{
    public static DesignTokens Light => new(
        ColorPrimary: AppColors.Primary,
        ColorPrimaryDark: AppColors.PrimaryDark,
        ColorSecondary: AppColors.Secondary,
        ColorBackground: AppColors.Background,
        ColorSurface: AppColors.Surface,
        ColorTextPrimary: AppColors.TextPrimary,
        ColorTextSecondary: AppColors.TextSecondary,
        ColorBorder: AppColors.Border,
        ColorOverlay: AppColors.Overlay,
        RadiusSm: AppLayout.RadiusSm,
        RadiusMd: AppLayout.RadiusMd,
        RadiusLg: AppLayout.RadiusLg,
        SpacingXs: AppLayout.SpacingXs,
        SpacingSm: AppLayout.SpacingSm,
        SpacingMd: AppLayout.SpacingMd,
        SpacingLg: AppLayout.SpacingLg,
        FontSizeSm: AppTypography.FontSizeSm,
        FontSizeMd: AppTypography.FontSizeMd,
        FontSizeLg: AppTypography.FontSizeLg,
        FontWeightBody: AppTypography.BodyWeight.ToString(),
        FontWeightHeading: AppTypography.HeadingWeight.ToString());

    public static DesignTokens Dark => new(
        ColorPrimary: AppColors.Dark.Primary,
        ColorPrimaryDark: AppColors.Dark.PrimaryDark,
        ColorSecondary: AppColors.Dark.Secondary,
        ColorBackground: AppColors.Dark.Background,
        ColorSurface: AppColors.Dark.Surface,
        ColorTextPrimary: AppColors.Dark.TextPrimary,
        ColorTextSecondary: AppColors.Dark.TextSecondary,
        ColorBorder: AppColors.Dark.Border,
        ColorOverlay: AppColors.Dark.Overlay,
        RadiusSm: AppLayout.RadiusSm,
        RadiusMd: AppLayout.RadiusMd,
        RadiusLg: AppLayout.RadiusLg,
        SpacingXs: AppLayout.SpacingXs,
        SpacingSm: AppLayout.SpacingSm,
        SpacingMd: AppLayout.SpacingMd,
        SpacingLg: AppLayout.SpacingLg,
        FontSizeSm: AppTypography.FontSizeSm,
        FontSizeMd: AppTypography.FontSizeMd,
        FontSizeLg: AppTypography.FontSizeLg,
        FontWeightBody: AppTypography.BodyWeight.ToString(),
        FontWeightHeading: AppTypography.HeadingWeight.ToString());

    public static DesignTokens ForMode(bool isDarkMode) => isDarkMode ? Dark : Light;

    public string ToCssVariables() => string.Join("\n", new[]
    {
        $"--mx-color-primary: {ColorPrimary};",
        $"--mx-color-primary-dark: {ColorPrimaryDark};",
        $"--mx-color-secondary: {ColorSecondary};",
        $"--mx-color-background: {ColorBackground};",
        $"--mx-color-surface: {ColorSurface};",
        $"--mx-color-text-primary: {ColorTextPrimary};",
        $"--mx-color-text-secondary: {ColorTextSecondary};",
        $"--mx-color-border: {ColorBorder};",
        $"--mx-color-overlay: {ColorOverlay};",
        $"--mx-radius-sm: {RadiusSm};",
        $"--mx-radius-md: {RadiusMd};",
        $"--mx-radius-lg: {RadiusLg};",
        $"--mx-spacing-xs: {SpacingXs};",
        $"--mx-spacing-sm: {SpacingSm};",
        $"--mx-spacing-md: {SpacingMd};",
        $"--mx-spacing-lg: {SpacingLg};",
        $"--mx-font-size-sm: {FontSizeSm};",
        $"--mx-font-size-md: {FontSizeMd};",
        $"--mx-font-size-lg: {FontSizeLg};",
        $"--mx-font-weight-body: {FontWeightBody};",
        $"--mx-font-weight-heading: {FontWeightHeading};"
    });
}
