---
apiVersion: v1
kind: Service
metadata:
  name: mss-workforce-code-databasemanager
spec:
  type: ClusterIP
  selector:
    app: mss-workforce-code-databasemanager
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8443
    targetPort: 8443
